### ISSUE TITLE
Computed properties/selectors in array items

### ISSUE THREAD

**Issue by brettburley** [toranb/ember-redux#10]
An interesting problem I've run into is rendering arrays from the store. Take, for example:
```
var stateToComputed = (state) => {
  return {
    users: state.users.map((user) => ({
      fullName: `${user.firstName} ${user.lastName}`
    });
  };
};

export default connect(stateToComputed)(Ember.Component.extend({
  layout: hbs`
    {{#each users as |user|}}
      {{user-item user=user}}
    {{/each}}
  `
}));
```

Any time a user is added or removed to the state tree, `stateToComputed` must be recomputed, which produces an array of all new objects due to the map. Since all of the objects are new, Ember must re-render the complete loop and all of the `user-item` components in it.

In current releases of Ember 2.x, even if you set `users` to a new array, it will only re-render items in the each that are actual new objects. For example, `this.set('users', [...this.get('users'), User.create()])` would only require the rendering of the single new `user-item` component for the new user.

I have played with using https://github.com/reactjs/reselect along with `ember-redux`, however this doesn't solve the issue for adding/removing items to arrays, since `reselect` will recompute since the array object itself is new, and therefore Ember will have to re-render the entire array and every item within it.

Is this an issue you've run into? Any other ideas for approaches to computed properties for items within an array? I seem to come across this pattern of rendering data from an array relatively often.

**Comment by toranb** [comment]
@brettburley truthfully I assumed that using ember 2.x would solve the problem you mention because we only diff the DOM and re-draw items that have changed. In the case of add/remove you would only add new items to the view/or remove items from it. I didn't think a new array here would throw out the component (dom layout) entirely if the visible DOM was mostly identical.

I'm curious how you profiled this /or found it was costly => help level me up dude :)

**Comment by brettburley** [comment]
https://github.com/emberjs/ember.js/pull/10501 is a relatively good description of Glimmer (as it works now?). It's based on watching values and updating only the necessary parts of the DOM, rather than diff'ing a virtual DOM. Admittedly, I don't fully understand the details of Glimmer or its roadmap with references, validators, etc.

I made a [demo app](https://github.com/brettburley/ember-redux-map-example) in Ember 2.5.1 to play around with this a bit more. Here's the primary `stateToComputed` type of transformation (adding a `fullName` property to `users`) that I was testing:
```
const stateToComputed = (state) => ({
  users: state.users.map((user) => Object.assign({
    fullName: `${user.firstName} ${user.lastName}`
  }, user))
});
```
I'm rendering users in an each with a component:
```
{{each users as |user|}}
  {{user-list-item user=user}}
{{/each}}
```

Here are the three variations of rendering I tried:
1. `{{#each users as |user|}}`: Standard each helper.
2. `{{#each users key="id" as |user|}}`: Standard each helper using the key attribute. This serves as a hint of when the object is the same so that Ember can use the same each instance.
3. `{{#each memoizedUsers as |user|}}`: Standard each helper iterating over a memoized version of the array. I created a simple [`memoizedMap` function](https://github.com/brettburley/ember-redux-map-example/blob/master/app/controllers/application.js#L4) which will perform a `map` on an array of objects, but re-use previous results for objects that have already been transformed. This way, the result objects in the mapped array will be the same if the input objects are the same.

To instrument what was being re-rendered, I added a global counter on `init` of the component. I also created a `render-counter` Ember helper which uses a global counter as well, this way I could count how many times Ember is calling this helper. I dropped this in as `{{render-counter}}` to see when an entire component is being re-rendered, and dropped it in with `{{render-counter user.fullName}}` to see when Ember had to re-render due to the `user.fullName` property "changing".

Here are the results I saw:
![olhvq6vghz](https://cloud.githubusercontent.com/assets/8064362/14938097/5c219c6c-0ece-11e6-873b-59d5ea8ba7dc.gif)

For those three variations outlined above, here are the results I saw:
1. New components were instantiated when a new user was added. This is the most expensive outcome, as the old component has to be taken down, a new one set up, and completely rendered.
2. Old components were re-used and the only part that was re-rendered were places relying on `user.fullName` (likely because the user object itself changed).
3. Old components were re-used and nothing had to be re-rendered. Only the newly added user had to be rendered.

The result in the last case would seem to be the most ideal outcome. However, in order to achieve that, I had to create and use a memoized array map helper. I haven't come across this pattern in React apps (even though they do use memoization via `reselect` for simpler transformations), but it might be that they don't need that incremental performance since they're diff'ing at the DOM level.

**Comment by toranb** [comment]
@brettburley thanks for taking the time to build this demo app and try a few different scenarios! It got me asking more questions like "could this be a real performance concern in components that show a large amount of data?". The two data points you show are 1) how often each component is created and 2) how often "render" is invoked. From a quick look at the [glimmer][] issue on github it would seem that a call to "re-render" might not be problematic directly.

> In other words, the programming model is equivalent to "render every time", but we take advantage of the declarative nature of Ember's APIs to reduce work.
> ...
> When re-rendering, we walk the tree and flush the streams. If the primitive value produced by the stream has not changed, we do nothing. If it has changed, we write the change to the DOM. 

But without a much deeper understanding of glimmer, I'm honestly out of my depth here and couldn't say with confidence that this is/ or is not a real performance problem. I still think it's something valid to have on the radar but I believe the discussion will be more valuable/productive over on the ember github site itself. It may be the case that glimmer 2 solves this/or that it provides a hook for additional optimizations (when immutable data structures are in use for example).

Back to the original question - I didn't know about `reselect` before you opened this issue and truthfully relied on my assumption that glimmer and glimmer(2) would reduce any amount of the DOM thrashing that immutable data might introduce.

[glimmer]: https://github.com/emberjs/ember.js/pull/10501

**Comment by toranb** [comment]
@brettburley just checking in as I didn't hear anything from the reply above :)

One other item I thought to ask about is the performance waterfall graphs /or if you knew about performance monitoring tools that show more information than "created/render calls" . I also heard something today about glimmer vs glimmer 2 on "component creation cost" that made me think glimmer 2 would greatly reduce the "tax" or overhead that comes with creating a large number of components.

**Comment by brettburley** [comment]
> The two data points you show are 1) how often each component is created and 2) how often "render" is invoked.

Yes, I agree that (1) appears to be the more significant issue, assuming (2) is in fact handled by Glimmer's value diff'ing. Reading the [issue you linked](https://github.com/emberjs/ember.js/pull/10501), it seems like this behavior should already happening, so I want to look more into what's going on in the `{{#each users key="id" as |user|}}` example, since I don't expect it to re-render the `fullName` property since the value isn't changing (although the underlying data object is).

On the note of components being recreated, I think this certainly could be a performance issue in a larger application. If you imagine any kind of complicated list (blog comments, forum thread, table of data, etc.), each item in the list might be made of many components. Adding/removing things from the list mean that since the parent component is rebuilt, all of its child components too are destroyed and recreated. However, if the component creation cost becomes trivial (and the same DOM can be reused), then this might become moot.

> One other item I thought to ask about is the performance waterfall graphs /or if you knew about performance monitoring tools that show more information than "created/render calls" .

The only other tool I know is the Ember inspector plugin for Chrome. It can show view/component render times, which is super useful. However, the amount of time a component/`{{each}}` loop takes to render will be highly dependent on how many subcomponents are being rendered, how complicated each is, etc., so I don't think the times are too useful for this sample case. Although they might be interesting to capture as the base case, since a list can't get much more simple than this!

**Comment by toranb** [comment]
@brettburley the last few days I've been thinking "how can we make this issue something action-able" and I was curious if we could implement the glimmer 2 demo (from the 2016 EmberConf keynote) with ember-redux to see how it performs. I found a demos directory but I couldn't find the raw source code for that react/ember app. You have any available bandwidth in the next 30 days to help hunt down the source for that app w/ tons of components so we could measure the effort required to build it with ember-redux?

https://github.com/tildeio/glimmer/tree/master/demos

**Comment by toranb** [comment]
@brettburley closing this until either you/or I get some bandwidth to really build up a demo and test it w/ glimmer 2
