### ISSUE TITLE
afterInstall throws error

### ISSUE THREAD

**Issue by wolfbiter** [toranb/ember-redux#16]
fyi running `ember install ember-redux` throws error in `afterInstall`. i worked around by manually installing deps

```
afterInstall: function() {
    return this.addAddonsToProject({
      packages: [
        {name: 'ember-browserify', target: '^1.1.11'},
      ]
    }).then(function() {
      return this.addPackagesToProject([
        {name: 'redux', target: '^3.5.2'},
        {name: 'redux-thunk', target: '^2.1.0'}
      ]);
    }.bind(this));
```

**Comment by dustinfarris** [comment]
What version of Ember are you on?

**Comment by wolfbiter** [comment]
![image](https://cloud.githubusercontent.com/assets/1360563/17465367/0feb61fa-5caa-11e6-99ce-ca014ea086a4.png)

**Comment by dustinfarris** [comment]
Thanks.  Can you also post the error you are getting?

**Comment by toranb** [comment]
what version of ember-cli are you using?

**Comment by toranb** [comment]
@wolfbiter I haven't been able to reproduce this w/ anything modern but feel free to reopen if you run into issues again
