### ISSUE TITLE
need for ember-browerify

### ISSUE THREAD

**Issue by ksnyde** [toranb/ember-redux#21]
This isn't an issue so much as a question ... I notice both `redux` and the `redux-think` middleware are being included as part of the normal NPM build process but wasn't sure why you're using browserify and your **import** statements are "npm:redux", etc.

Second part of this would be ... would using SystemJS be a reasonable alternative or do you prefer Browserify?

Sorry for the silly question.

**Comment by toranb** [comment]
I thought this addon (ember-browserify) was the secret to using redux in ember with ES6 but it's possible I'm out of date or touch :)

Do you have example that shows this working without any additional hacks in ember? I'd love to reduce the deps required to use redux with ember-cli

**Comment by dustinfarris** [comment]
As far as I know, ember-browserify is the most straight-forward way to bring in npm dependencies.  I was just talking about this on Slack yesterday and everyone seems to agree.  @ksnyde have you used SystemJS successfully in an addon?  I have not seen this approach and am curious to know more about how well it works with broccoli and ember-cli.

My understanding is that the thinking on managing JS dependencies (better support for npm JS deps, dropping bower, etc..) is currently tied up with other considerations for things like engines.

Here is an open ember-cli issue that touches on it: https://github.com/ember-cli/ember-cli/issues/4211

**Comment by dfreeman** [comment]
For packages distributed with UMD/globals builds, a number of addons are [using ember-cli-node-assets](https://www.npmjs.com/browse/depended/ember-cli-node-assets). The addon is basically just sugar for creating a broccoli tree for an npm package and then `app.import`ing stuff from it, without all the extra build effort and runtime machinery that Browserify requires.

To support stuff like `import redux from 'redux';` you could either package a [vendor-shim](https://github.com/ember-cli/ember-cli/tree/4b8f028dae2fa5b7cdfa7cde5c0f74ceef1f85b8/blueprints/vendor-shim) or try out the fancy new [anonymous AMD support](https://github.com/ember-cli/rfcs/blob/master/active/0000-anonymous-amd.md) that landed in [this ember-cli PR](https://github.com/ember-cli/ember-cli/pull/5976).

**Comment by ksnyde** [comment]
@dustinfarris there was a great video from a guy in Germany about his experience with SystemJS and Ember (and I know he was talking to the core team at that point). I know that a lot of people believe SystemJS is better solution outside the Ember landscape but I'm really not an expert on either. Let me see if I can dig up a link for that video though ... here it is:

[SystemJS, JSPM, and Ember](https://www.youtube.com/watch?v=lc9nQJR6RX4)

Came out in late 2004 so it's a bit dated but I think many of his points are still worthy of a watch if you're interested.

**Comment by dustinfarris** [comment]
@dfreeman how do vendor-shims and/or anonymous AMD support enable you to import from node_modules?

**Comment by dustinfarris** [comment]
oh, i think i see what you mean.  do the ember-cli-node-assets first, then do a shim on top of it?

**Comment by dfreeman** [comment]
@dustinfarris Exactly — ember-cli-node-assets gets the actual libraries into the build, and then the shim just exposes the relevant bits in a way that `loader.js` can find them.

**Comment by toranb** [comment]
@ksnyde so ... did the question morph into a set of actionable steps or no? I'm all for someone taking a look into ember-cli-node-assets but keep in mind that I'm focused on having the addon work with ember-twiddle (thanks to @dustinfarris for making this happen), the ember-install story remains just as simple/easy as it is today and most importantly :) we keep the addon stable for those using it. I can't prioritize this task myself because other parts of the redux + ember stack need my attn at the moment, and this isn't truly causing me any grief personally.

**Comment by ksnyde** [comment]
sure @toranb I completely understand; really glad your focus has delivered so much value already. I'm also a bit low on bandwidth and this "issue" was more of an inquisitive ask so I think unless there's a reason to keep it open we should just close this issue.
