### ISSUE TITLE
use app.import instead of browserify

### ISSUE THREAD

**Issue by aaminev** [toranb/ember-redux#28]
looks like in ember-cli v2.9 or 2.10 there is a new way for importing amd modules
```js
app.import('vendor/a-file-from-the-folder-above.js', {         
   using: [{ transformation: 'amd', as: 'some-package' }]        
});
```
I wonder if we can use it instead of browserify and `npm:*` syntax

cc @MiguelMadero

**Comment by dustinfarris** [comment]
i don't think this replaces browserify

**Comment by MiguelMadero** [comment]
Browserify does a few more things to build and consume CJS, but the redux node_module includes a pre-built file that uses UMD and the above syntax can import AMD. Totally untested, but it may work if we `ember install ember-cli-node-modules-to-vendor` and then do something like:

```
var app = new EmberApp(defaults, {
  nodeModulesToVendor: [
    'redux': 'node_modules/redux/dist/'
  ]
});
app.import('vendor/redux/redux.js', {         
   using: [{ transformation: 'amd', as: 'redux' }]        
});
```

Then in the app simply `import redux from 'redux'`. I'll try that out later and update the issue. I'm not super familiar with browserify and might be missing something else.

**Comment by dustinfarris** [comment]
Oh, interesting!  Yeah that looks like it might work (for packages with dist files anyway).

**Comment by aaminev** [comment]
@MiguelMadero keep in mind that there are another packages, like `redux-thunk` or `redux-logger`, both contain dist folder though, so should be the same.

**Comment by toranb** [comment]
@aaminev @MiguelMadero how does this work if I want to support both ember 2x and 2.9+ ?

**Comment by dustinfarris** [comment]
I was also thinking— while this is a neat trick, the ember-cli team is actively working on a bona fide solution for bringing in npm modules, and in the mean time ember-browserify is still recommended.  I think we should stick it for now.

**Comment by MiguelMadero** [comment]
@toranb this is more about CLI, not ember. It may be possible to do it in a backwards compatible way, but that may be step 2 after/if it works. 

@dustinfartis the packager work is a more complete solution that solves other problems as well, like tree shaking. This approach already works for a lot of common use cases (not sure if thats the case here). Anyway, I understand your point and thats a valid position.

**Comment by dustinfarris** [comment]
I was also thinking— while this is a neat trick, the ember-cli team is actively working on a bona fide solution for bringing in npm modules, and in the mean time ember-browserify is still recommended.  I think we should stick it for now.

**Comment by toranb** [comment]
@MiguelMadero if you or @aaminev land something that works with ember-cli and allows us to remain backwards compatible with ember 2+ I'd be happy to look over a pull request :) 

The interesting part for me here is mostly that of priority /importance - In my app code I never once import anything from the "npm:redux" package -that only occurs in this addon and only 2x total.

1) once in the service itself to fetch redux
2) once in the default middleware to fetch redux-thunk

For now I'm planning to close this out until we know more/ or someone has some code to show off :)

**Comment by MiguelMadero** [comment]
Hi @toranb I'll try to have a quick stab next time I'm working on ember-redux. The main reasons to do this are: 

1) Reduce the payload. We need to get some numbers, and I'll get those on that PR, but it was adding a few important kbs just having browserify. 
2) Improve the build time, browserify is our slowest on cold and warm builds (almost 2 seconds).

**Comment by toranb** [comment]
@MiguelMadero good to know that it does benefit by way of smaller payloads and faster build times (dumping browserify that is). 

If the solution is to do something like the below (as you mentioned a while back) - does this go in the ember-cli-build of the consumer? or index.js of the addon? or some other place altogether ?

```js
var app = new EmberApp(defaults, {
  nodeModulesToVendor: [
    'redux': 'node_modules/redux/dist/'
  ]
});
app.import('vendor/redux/redux.js', {         
   using: [{ transformation: 'amd', as: 'redux' }]        
});
```

**Comment by dustinfarris** [comment]
ember-cli-node-modules-to-vendor got a ringing endorsement from ember-browserify 

https://github.com/kellyselden/ember-cli-node-modules-to-vendor/issues/2#issuecomment-263337894

We can probably reopen this issue

**Comment by MiguelMadero** [comment]
He did a good summary :)
