### ISSUE TITLE
Example twiddle appears to be broken

### ISSUE THREAD

**Issue by sohara** [toranb/ember-redux#29]
I'm not sure if this is an issue with twiddle itself or some issue with another dependency but it appears that the example twiddle is broken: https://ember-twiddle.com/7ce3446b14f166f04064eba663c0a350

I just get a flash message saying 'process exited before completing request'

**Comment by toranb** [comment]
Huh, just tried it in chrome on OSX without issue - what browser and operating system are you using?

**Comment by toranb** [comment]
@sohara a little more research and it appears that on OSX both chrome/firefox work but Safari doesn't. Depending on what browser you are using, we could investigate further, possibly create an issue with twiddle itself

**Comment by sohara** [comment]
@toranb Sorry I didn't get back to you. I was using Chrome at the time but it seems to be working now. Possibly my Chrome auto-updated in the interim.

Thanks for the response, enjoying ember-redux so far!

**Comment by toranb** [comment]
@sohara no worries! Glad its working in chrome - I honestly never dev in Safari myself but found it interesting that iOS 10 safari is fine.
