### ISSUE TITLE
Redux/redux-thunk must be npm-installed on the host app

### ISSUE THREAD

**Issue by brettburley** [toranb/ember-redux#3]
@toranb thanks for putting this together, this is really awesome!

From my experience with using this addon, I had to `npm install` `redux` and `redux-thunk` for it to compile properly.

It appears that this is a known limitation with `ember-browserify`:
https://github.com/ef4/ember-browserify
> To have the host app consume the npm dependency, ember-browserify and the npm dependency must be installed in the host app as well AND the module must be imported from within the app/ directory of the addon. So in your app, simply npm install ember-browserify and whatever npm dependencies you need consumed by ember-browserify.

It doesn't look like https://github.com/toranb/ember-redux-example/ includes `redux` or `redux-thunk` in it's `package.json`, so I'm curious about your experience with this.

**Comment by toranb** [comment]
@brettburley honestly I assumed having `redux-thunk` in the [dependencies][] block of the package.json was enough. When I install this in any modern ember app I don't get any type of compile error with ember-cli.

What versions of ember-cli / ember / and ember-browserify are you using? If you use the versions you see below everything should be solid? Here are 2 examples worth looking at

ember-cli v2.4.2 and v2.4.3
ember-browserify v1.0.2
ember v2.4

https://github.com/toranb/ember-redux-ddau-example/blob/master/package.json
https://github.com/toranb/ember-redux-example/blob/master/package.json

[dependencies]: https://github.com/toranb/ember-redux/blob/master/package.json#L57

**Comment by brettburley** [comment]
Both of those repos failed for me locally (Max OS X). It appears to be a result of the latest `ember-browserify v1.1.8`. If I downgrade to `v1.0.2` as suggested, it seems to work fine.

For reference, here's the error I get with `v1.1.8`:
```
The Broccoli Plugin: [object Object] failed with:
Error: Cannot find module 'redux' from '/Users/brettburley/Git/ember-redux-ddau-example/tmp/core_object-input_staging-zXLMsE6R.tmp'
```

I haven't investigated to see why `ember-browserify` seems to have regressed (although the behavior I'm seeing with `v1.1.8` seems to be consistent with their documentation).

**Comment by toranb** [comment]
Huh so I just bumped both of those examples to ember-browserify v1.1.8 and they work w/out error

https://github.com/toranb/ember-redux-ddau-example/commit/d9f87e3882576c4ea4f72f5e8f57493563651947

https://github.com/toranb/ember-redux-example/commit/14873188339547cadb2320f2fe84ff4eb363e111

What version of node/npm are you using? I'm using node v5.6.0 and npm v3.6.0

**Comment by brettburley** [comment]
Interesting... I think my "success" with `v1.0.2` was a red herring because while it built successfully, it didn't actually include `redux` or `redux-thunk` in the build. It looks like `ember-browserify >1.1` is required to work with `ember-cli 2.x`.

I was using `node 0.12.4`. Upgraded to `v5.10.1`, but am seeing the same error. I have `npm 3.8.3`.
```
$ ember --version
ember-cli: 2.4.3
node: 5.10.1
os: darwin x64
```

Tracing this a bit more, it does look like it will recursively look for a `node_modules` folder in every parent directory above the current project to resolve the package. Do you perhaps have a `node_modules` folder in one of the parent directories of `ember-redux-ddau-example` or `ember-redux-example` that might have `redux` and `redux-thunk`?

**Comment by toranb** [comment]
So I tried the install process on another MacBook and wouldn't you know it - busted without redux and redux-thunk in the main app ... That was using node v4.2.6 but it's enough to say we should update the install steps to include these both.

I'll likely need to support redux-thunk 1.0.x and 2.0.x

**Comment by toranb** [comment]
This is now correctly mentioned in the readme and v1.2.0 of `ember-redux` now supports both `redux-thunk` v1.x and v2.x
