### ISSUE TITLE
[RFC] expose an api similar to ember's initializer for redux users to build middlewares

### ISSUE THREAD

**Issue by foxnewsnetwork** [toranb/ember-redux#34]
- Start Date: (fill me in with today's date, 2016 - Halloween Weekend)
# Summary

Use [ember-redux-load-middlewares](https://github.com/foxnewsnetwork/ember-redux-load-middlewares) to allow app and addon users of ember-redux to create middlewares and enhancers and have them automatically included in `ember-redux`'s store setup phase
# Motivation

Right now, if we wanted to add other stuff to our middlewares, enhancers, or even reducers stack, we necessarily have to write our own `reducers/index.js`, `middlewares/index.js`, etc., file, copy over the file contents in `ember-redux`'s `app/reducers/index.js`, and cobble together our own thing. From an ember user's point of view, stringing together enhancers, middlewares, and reducers feels a lot like how ember's initializers should work, and it'd be great if we could provide a similar API
# Detailed design

The `ember-redux-load-middlewares` addon shamelessly copies how stefan penner's ember-load-initializer works and uses the `_eak_seen` property of `requirejs` to find out all the initializers an user might have in his or her `app/reducers`, `app/middlewares`, and `app/enhancers` folders.

On `ember-redux`'s side, we would do:

``` javascript
import {
  loadReducers,
  loadMiddlewares,
  loadEnhancers
} from 'ember-redux-load-middlewares';

const reducers = loadReducers('my-app')
const middlewares = loadMiddlewares('my-app')
const enhancers = loadEnhancers('my-app')
```

to get all the `reducers`, `middlewares`, and `enhancers` an user would like to have in the app. Like ember's initializers, the loaded reducers, middlewares, and enhancers are actually a hash that looks something like this:

``` javascript
type loadedReducer = { 
  reducer: Reducer
  name: String,
  before?: [String],
  after?: [String]
}
```

Presumably, on `ember-redux`'s end, we could copy how `ember` handles sorting initializers and sort our reducers, middlewares, and enhancers before composing them together for the user's app to consume.

The `ember-redux-load-middlewares` addon also ships with blueprints to help the user generate reducers, middlewares, and enhancers:

``` bash
ember generate redux-enchancer my-enchaner
ember generate redux-middleware my-middleware
ember generate redux-reducer my-reducer
```
# How We Teach This

There really isn't much to teach here; users of ember should already be familiar with how initializers work, and users of redux should be familiar with how reducers, enhancers, and middlewares work. Assuming this is true, we're simply providing an easier and more familiar and less boiler-plate filled way of allowing these users to work with redux in their ember apps.
# Drawbacks

The main drawback is if the user has an extremely complicated middleware / enhancer / reducer stack that can't be strung easily together like ember's initializers could. The most likely source of such complexity would likely result from the users putting asynchronous actions in how their reducers / enhancers / middlewares are declared, and ostensibly such an usage would be made even more difficult to implement than it already is. Luckily, I don't think too many folks on redux are doing this.
# Alternatives

An alternative design would be to somehow straight-up wrangle ember's initializers to mix this stuff together.
# Final Thoughts
- If we're good with this idea, I can work on a PR for implementing it
- full disclosure: I personally need something like this because I'm currently making an addon https://github.com/foxnewsnetwork/ember-apollo for the apollo-client (redux's graphQL implementation) for ember, and I kind of need a way to merge the stores

**Comment by toranb** [comment]
@foxnewsnetwork thanks for taking the time to write up such a formal draft of your thoughts around this issue! I've got a few points to consider but plan to wait a few days so that others in the community can reply without bias :)

**Comment by brettburley** [comment]
I really like the idea that an addon could register its own middleware, etc. This could open up the possibility of addons that require no configuration out of the box. However, I'm worried about the loss of explicitness, particularly with reducers.

How would the state shape be defined in this schema for reducers? And in particular, would you expected only top level reducers to be included (and thus they should export objects that may include reducers from nested folders), or would an entire tree of reducers be included?

**Comment by foxnewsnetwork** [comment]
>How would the state shape be defined in this schema for reducers? And in particular, would you expected only top level reducers to be included (and thus they should export objects that may include reducers from nested folders), or would an entire tree of reducers be included?

This is a really good point you bring up, and at least in my own dog-food-ing use-case with trying to port graphQL's apollo-client into ember (and other similar ember-redux addon projects), I would imagine the reducer combination to work something like so:

- ember-apollo
  - addon
    - reducers
      - first-reducer.js
      - second-reducer.js
      - third-reducer.js
      - blue-reducer.js
      - red-reducer.js
  - app
    - reducers
      - ember-apollo.js

Then, in the `app/reducers/ember-apollo.js` file, we'd have something like:

```javascript
import { reducer as first } from 'ember-apollo/reducers/first-reducer';
import { reducer as second } from 'ember-apollo/reducers/first-reducer';
import { reducer as third } from 'ember-apollo/reducers/first-reducer';
...

function combineReducers(...args) {
  ...
}

export default {
  name: 'ember-apollo',
  reducer: combineReducers(first, second, third)
}
```

> However, I'm worried about the loss of explicitness, particularly with reducers

So this is a super valid concern, but I don't think we'd actually lose this because, in an end user's ember app, the end-user would still be able to overrwrite the `app/reducers/index.js` file.

Notably, suppose this RFC is accepted and `ember-redux/blueprints/ember-redux/files/reducers/index.js` file is added,

```javascript
import { loadReducers, runReducers } from 'ember-redux-load-middlewares';

const reducers = loadReducers('my-app');
let myAppReducers = {};
runReducers(reducers, (name, reducer) => myAppReducers[name] = reducer)

return default myAppReducers;
```

The users who desires more customization may modify the end-consumer app's `reducers/index.js` file as they see fit by doing something like:

```javascript
import Ember from 'ember';
import { loadReducers, runReducers } from 'ember-redux-load-middlewares';

const { getWithDefault } = Ember;
const ID = (x) => x;
const reducers = loadReducers('my-app');
let myAppReducers = {};
const CUSTOMIZER = {
  'ember-redux-addon-reducer': function(reducer) {
    return doSomeStuff(reducer);
  },
  'ember-redux-other-reducer-addon': function(reducer) {
    return doOtherStuff(reducer);
  }
};
runReducers(reducers, (name, reducer) => { 
  myAppReducers[name] = getWithDefault(CUSTOMIZER, name, ID)(reducer) 
});

return default myAppReducers;
```

But please, let me know what you think; do you have any ideas what short-comings there might be hidden in this? If so, how can we improve it? thx

**Comment by toranb** [comment]
@foxnewsnetwork My feeling is that we are talking about a core design decision here

```
    explicit vs implicit
```

Your pain point seems to be that we are asked to explicitly add a reducers/index.js file (or the equiv for middleware/enhancers). You would prefer an implicit setup instead -correct?

My "alternative" approach is that we embrace explicit and add the additional code required. If someone needs to have a certain order for some middleware (an open issue already mentions this requirement) - the user can do what they need/without anything special.

My second concern is the dependency - the moment we rely on something outside of this addon to make this work (beyond redux/redux-thunk) I begin to question if we are instead building some type of framework. Why couldn't we keep this core library solo and offer the ability for users to "bolt on" implicit as needed/desired?

I would assume someone could ember install this, then your library and be off to the races. In fact, that approach would show just how robust both of these addons are independently.

My third concern is that of fragmentation. Today you can simply add a reducers/middleware/enhancers directory and it should operate from that point like any react/or angular app using redux. As we begin to layer "ember-y" specific jargon (vocabulary) or addons, we also begin to fragment and in doing so futher separate this library from the core of redux itself.

One of my main motivations for writing ember-redux was that you could easily pivot between a react/angular/ember projects and not think twice regarding basic data flow/redux configuration/dev tooling.

**Comment by foxnewsnetwork** [comment]
The `implicit v. explicit` thing is a really good point, and I can totally see the value of keeping `ember-redux` as independent as possible - you make a really good point about not making `ember-redux` become a framework.

That said though, I personally do think it's in the best interest of Ember and all of us `ember-redux` users to attempt to gobble market share from both ember and react, and in that vein, I do think we should at least write up more ember flavored guides, cookbook recipes, and code snippets in `ember-redux`'s dummy app to so-to-speak sell this product to the community. In addition to the great stuff you already have on the ember-redux site, we could also put in stuff about conventional ways to chain middlewares, use enhancers, interface with the ember-router, use graphQL with apollo / cashay, etc.

What do you think about that approach? Instead of making the code-base opinionated and (as DHH puts it) "omakase", we answer all the common use cases and patterns in the docs, and leave the code simple and explicit.

**Comment by toranb** [comment]
@foxnewsnetwork I've spent the last 90 days building a yelp clone with ember-redux so I could produce a legit "step by step" guide showing how to use ember and redux in the wild. I even went so far as to turn that example into a stand alone ember-twiddle so people can play with it.

https://ember-twiddle.com/64b18c23223fbc1f3a7da8171c6d8881

Currently I'm rebuilding it from the ground using a "commit by commit" like process via github so I can construct a set of written guides that are easy to follow.

https://github.com/toranb/ember-redux-yelp/commits/master

From this I also plan to ship a set of companion videos on the subject (maybe even some test driven content as my training planned for this month was a no/go)

I'm all for ideas to help improve this and hope the guides I've been working on are at the very least one answer to the education problem you mention. Mostly the bottleneck is time as you might imagine - when I'm not at my day job/ or with the family I'm here replying to PRs/Issues or on slack talking with people about how they've come to love the ember-redux api and what I can learn to improve it. I usually get a few hours a week to crank on the guides/screencast work so you can imagine it's going slower than I hoped :) but I'm persistent and want a level of quality that beginners will be happy with.

**Comment by foxnewsnetwork** [comment]
@toranb wow, that is really awesome! Totally understand the issue on time (lol I too am a corporate peon), but I will definitely follow your example and write up some examples cookbook recipes for using ember-redux IRL.

**Comment by toranb** [comment]
@foxnewsnetwork do you want to close this out and open a new PR with a skeleton/outline of your plans for the cookbook work you mention? What we have today is fairly weak as you mentioned and I'd love to see what you have planned - I could also layout in that same issue what I have planned for the written guides that show "building yelp w/ ember-redux"

**Comment by foxnewsnetwork** [comment]
sure, I will close this issue and open up a new PR when I have more content for it
