### ISSUE TITLE
1.9 introduced regression in updateProps

### ISSUE THREAD

**Issue by dbashford** [toranb/ember-redux#48]
This did not occur in `1.8`.

We've got a ton of components so it's a bit hard to track this down, but wanted to report what i saw in case it screams at anyone straight away.

Here's a bit of ember-redux code where I tossed a `console.log`

![image](https://cloud.githubusercontent.com/assets/581127/20498806/8d7b8352-affc-11e6-9dbf-9001b418c084.png)

This `_state` is an Ember thing, not a Redux thing.

Upon clicking an icon in our app, which triggers a state change, this is the output I see

![image](https://cloud.githubusercontent.com/assets/581127/20498870/d97cac54-affc-11e6-9094-0895220878f6.png)

249 components which report a `_state` as being `inDOM` and everything works fine.

1 component that reports a `_state` of `preRender` and then the __next line__ breaks.

22 components which report a `_state` of `undefined` which could be because of the breakage above it.

**Comment by toranb** [comment]
@dbashford ouch - not good (sorry for the regression here)

In the short term - can you drop this into your node_modules and see if it's a quick win (no regression)? If yes we can patch this back tonight and learn more about what broke for you (curious myself)

(below was the connect source just before the big setProperties re-work)

https://github.com/toranb/ember-redux/blob/cfc1d2688034040fad1c15a520c79929d508c49d/addon/components/connect.js

**Comment by dbashford** [comment]
You need me to do that to prove something out on your end? If not, I'm cool hanging at 1.8 for awhile. No rush.

**Comment by toranb** [comment]
@dbashford mostly to confirm (for you) the 1 commit that did cause the break :) to help us narrow it down. I'd love if you could reproduce this with just a handful of components in a twiddle but didn't know if it was possible

**Comment by dustinfarris** [comment]
@dbashford anything special about the components that are "_state === undefined"?

The `init` of the wrapped component sets an empty object for the `_props` property, so it's odd that it becomes `null` at some point in your application.  I wonder if _props is reserved elsewhere.  I'll dig into that.

**Comment by dustinfarris** [comment]
@dbashford what version of ember are you on?

**Comment by dbashford** [comment]
It's hard for me to ignore the `preRender` thing. That's the only piece of data that changes from component to component prior to the breakage besides those things you'd expect to change.  In the screenshot above you can see 249 components are `inDOM` but as soon as one is `preRender` things shut down.

This might be really hard to prove out in a twiddle. But I may be able to narrow what is going on in our app down a bit.

We do a lot of lazy rendering (though not enough as evidenced by the 300 components we churn through to render the page), hard to say if that would have something to do with this.

We are on `2.8`.

**Comment by dbashford** [comment]
@toranb I'll check that bit of code in a bit, had moved onto something else

**Comment by dustinfarris** [comment]
@dbashford are you by chance using ember-react?

**Comment by dbashford** [comment]
Nope!

**Comment by dustinfarris** [comment]
I don't see anything where `_props` might be clobbered (although it might not be a bad idea to namespace this anyway).

I suspect the regression here lies elsewhere.

**Comment by dustinfarris** [comment]
I've experimented a bit more and having trouble reproducing even in preRender state:

![screenshot 2016-11-21 17 45 39](https://cloud.githubusercontent.com/assets/1087165/20503849/8a24db02-b012-11e6-82e2-227583789d0c.png)

There are 2 cases where `updateProps` is called.  Once in the Component `init` method, and again every time there is a redux state change (via subscribe).  I wonder in which case this error is triggered?  

If you could throw a `console.log('via init')` above the call to updateProps in init, and a `console.log('via redux subscribe')` above the call to updateProps in the subscribe handler (defined further down in the init method), and paste the output that would be helpful.

**Comment by dbashford** [comment]
@toranb I tossed that old code in and it worked, so that narrows down the commit.

@dustinfarris tossed in the code from your PR, the issue remains.

Made these changes

![image](https://cloud.githubusercontent.com/assets/581127/20525907/9f597924-b08f-11e6-9036-aa621f3057c1.png)

Got this

![image](https://cloud.githubusercontent.com/assets/581127/20525913/aaaeedea-b08f-11e6-8cd1-9f1b3441beed.png)



I have to jump on a few other things this morning, but hope I can double back to dig into this a bit later.

**Comment by dustinfarris** [comment]
Thanks for the quick feedback.  That information is helpful.  I'll continue digging in.

**Comment by toranb** [comment]
@dbashford I spent some time tonight trying to stand up my first engines app w/ lazy loading and currently had no success. Would it be possible to have you stand up a simple app w/ engines to show the most simple lazy loading scenario you have in your production app so I can emulate it here /in hopes of understanding what caused this regression (as I assume it's lazy loading of components w/ engines that is the big diff I'm not able to see myself)

**Comment by dbashford** [comment]
So we use engines, but not lazy loading just yet. I likely misspoke before, what I meant was lazy rendering. We use ember-spaniel. I'm mired in some run loop testing hell right now with our build, when I come out the other side I hope to start commenting out some components to see if I can get a fix on the minimum needed to reproduce this in our app

**Comment by toranb** [comment]
@dbashford I published v1.9.1 w/ a revert back to the working connect implementation. Please confirm it's g2g for you so I can feel like we have stabilized the addon (when you have time).

I'm leaving this issue open so you can help us determine what broke and why to help educate us on how others are using this addon in the wild. Thanks for reporting this instability!

**Comment by toranb** [comment]
@dbashford I've published v1.9.2 w/ the performance work you tested in PR #51 

take this new release for a spin this week/or next and let me know if you run into any trouble

**Comment by dbashford** [comment]
Will do, thanks!

**Comment by dbashford** [comment]
Just remembered you had asked about this, we're running `1.9.2` and all is good.

**Comment by toranb** [comment]
@dbashford awesome! thanks for reporting stability !!!
