### ISSUE TITLE
Add "ownProps" argument for stateToComputed/dispatchToActions

### ISSUE THREAD

**Issue by dustinfarris** [toranb/ember-redux#54]
This is something react-redux does.  For us it might look like:

```hbs
{{user-detail userId=567}}
```

```js
const stateToComputed = (state, ownProps) => {
  return {
    user: getUserById(state, ownProps.userId)
  }
}
```

I think this should be simple to add.  react-redux defines this argument as

> the props passed to your component

so we're not talking about all possible properties on the Ember Component, just what was passed to it, which Ember stores in `attrs`.

We can pass in attrs to the functions, and then listen to [didUpdateAttrs](https://github.com/emberjs/ember.js/blob/v2.10.0/packages/ember-glimmer/lib/component.js#L354)

so connect would be something like

```js

...

handleChange() {  // and also in init
  ...
  let props = stateToComputed(redux.getState(), this.attrs);
  ...
},

didUpdateAttrs() {
  this.handleChange();
}
```

**Comment by dustinfarris** [comment]
Unless someone sees something wrong with this, I will spin up a PR tomorrow.

**Comment by wooandoo** [comment]
Hello,

I suggest:
```js
const attrValues = (attrs) => Object.keys(attrs).reduce((result, key) => {result[key] = attrs[key].value; return result}, {});

// ...

let props = stateToComputed(redux.getState(), attrValues(this.attrs));

didUpdateAttrs() {
  this._super(...arguments);
  this.handleChange();
},
```

This avoids to get "value" for me:
```js
ownProps.userId.value
```

Frédéric

**Comment by dustinfarris** [comment]
Great suggestion! 👍 thanks!

**Comment by toranb** [comment]
@dustinfarris can we close this issue out and drive the discussion from that open PR ?

**Comment by dustinfarris** [comment]
@toranb I put a close hook in the commit message so this should close automatically once merged to master—not sure what organizational policy you prefer in terms of managing open issues/prs.  Maybe we should discuss offline someday to get on same page.

**Comment by toranb** [comment]
@dustinfarris ah right on :)
