### ISSUE TITLE
[Ember 2.10] Uncaught Error: infinite rendering invalidation detected

### ISSUE THREAD

**Issue by dbashford** [toranb/ember-redux#64]
2.10 introduced Glimmer 2. Glimmer 2 introduced [infinite rendering invalidation detection](https://github.com/emberjs/ember.js/blob/855363285dc66ece8eac9f417375bd4d69460e7e/packages/ember-glimmer/lib/renderer.js#L149-L163). Not entirely sure what that is, haven't dug enough.

We have a master detail layout in our app, and the detail panel is what uses redux. We have it carved out as an addon.

When a user clicks the first item, none of the detail components exist yet. The detail panel slides in, the detail addon top level component is rendered with a handful of inputs, it makes a few server calls and renders all the things.

When a user clicks a second item, because the panel is already open, we have ~15ish components already bound to state and listening for updates. Clicking the second item passes in a bunch of inputs which are immediately `dispatch({ type: INITIALIZE: payload: inputs})` into state.

There are enough components listening to some of the inputs that `handleChange` is called a good number of times.  Too many.  And then that error happens and things explode.

There are definitely steps I can take to reduce the number of components bound into state.  I can also do some work to [batch some actions](https://github.com/tshelburne/redux-batched-actions) so that synchronous actions that happen to have some overlapping state do not get updated multiple times.

But I can absolutely foresee, post improvements, still having this issue and being forced to destroy most all of the detail before I do anything with the new inputs so that components aren't listening for changes. In some cases this might be the ideal thing to do anyway, and I expect that'll be one of the best improvements I can make, but in some it isn't ideal.

Not sure exactly what ember-redux can do differently to smooth this over, but I'd guess it'll be something other folks run into at some point.

**Comment by dbashford** [comment]
FWIW, redux-batched-actions doesn't do what I stupidly through it would do. It accumulates actions, but still executes them in succession.

This has turned into a major deal breaker.

Let me know if there is something I'm missing with Redux but...

I have lets say 10 components bound to state. I update some state. All 10 components have their `handleChange` called.  I call 3 or 4 actions in succession (practically at the same time), (`INITIALIZE`, `BEGIN-LOAD-DATA-A`, `BEGIN-LOAD-DATA-B`, etc) that is 3 or 4 updates to state and 30/40 calls to `handleChange`. This breaks Ember.

The only thing I've tried that seems to help a little is `run.debounce(this, this.handleChange, 50);` but even that just postpones the problem. It stops the same component from having its `handleChange` called over and over, but if I have enough components...

**Comment by dustinfarris** [comment]
Interesting.  I wonder if the change/discussion in #59 would be of assistance here.  Can you try that branch and see if it makes a difference?

**Comment by toranb** [comment]
@dbashford thanks for the update - it seems we need a more complex test case /example of many components with many handleChange calls (on G2/ember 2.10). One thing that leaps to mind is what the most simplistic example might look like here - any chance you have time to stripe this down to something fairly basic so we can reproduce/learn from your setup?

Honestly would love to see what broke this and how we can improve the handleChange (subscription) callback to accommodate

**Comment by dbashford** [comment]
I didn't try anything from that PR because it felt like simply adding to the run loop, no matter what it was, was causing trouble.

I even went so far as to do something like this and still got the errors.

```javascript
const redux = this.get('redux');
let props = stateToComputed(redux.getState());
const notifyProperties = [];
Object.keys(props).forEach(name => {
  if (this.get(name) !== props[name]) {
    notifyProperties.push(name);
  }
});

if (notifyProperties.length > 0) {
  run.debounce(() => {
    notifyProperties.forEach((name) => this.notifyPropertyChange(name));
  }, 50);
}
```

So limiting entries into the run loop to just those components with updated state, and debouncing to prevent the same component from notifying over and over (even though that wouldn't technically be good for the app, I was grasping at straws).

COB yesterday I *think* I finally got the app working again, but at this point I've piled hack on hack. Time to remove those one at a time to see what did the job. And I gave up making updates to ember-redux to try and get things working. Eventually just started to modify app code to try and avoid the problem.

It'll take at least the day to get this right. Hopefully will have a useful post mortem.

**Comment by dbashford** [comment]
Started from scratch and added things I learned yesterday one at a time. I quickly got to the few things causing me trouble. 

When the errors were first seen, the stack trace took us back to `handleChanges` every time. As I started eliminating redux usage yesterday, another piece of code in our app became the problem.  So it isn't ember-redux alone, more of a larger run loop usage theme.

We are using ember-spaniel for viewport tracking. We have SpanielObserver being registered on `didInsertElement` for a component that can be rendered 10-30 times on the page.  It was being registered like this

```javascript
    const observer = new SpanielObserver(([entry]) => {
      run(() => {
        this.set('viewportEntered', entry.entering);
      });
    }, options);
```

That `run` is called immediately for any components within a certain distance of the viewport.  At most 16 times all at once.

Changed it to:

```javascript
    const observer = new SpanielObserver(([entry]) => {
      run.scheduleOnce('afterRender', () => {
        this.set('viewportEntered', entry.entering);
      });
    }, options);
```

And things got better.  But the app didn't fix until this was also changed in ember-redux:

```javascript
this.unsubscribe = redux.subscribe(() => {
  run(() => this.handleChange());
});
```

turned into this:

```javascript
this.unsubscribe = redux.subscribe(() => {
  run.next(() => this.handleChange());
});
```

Both of the above changes are necessary to get us to a happy place, at least without making more modifications. Still re-doing a lot of tweaking from yesterday to see if I can get to a point where the `run.next` isn't required.

**Comment by dbashford** [comment]
And so as to keep spamming all this repo's watchers...

Once I fixed a few other things in my app, including the Spaniel stuff, then this worked as an alternative to just using `run.next`. Maybe it's best to not bother Ember until you know you need to?

```javascript
const redux = this.get('redux');
let props = stateToComputed(redux.getState());
const notifyProperties = [];
Object.keys(props).forEach(name => {
  if (this.get(name) !== props[name]) {
    notifyProperties.push(name);
  }
});

if (notifyProperties.length > 0) {
  run(() => {
    notifyProperties.forEach((name) => this.notifyPropertyChange(name));
  });
}
```

**Comment by toranb** [comment]
@dbashford wow this is an epic find -can't believe we didn't take more care w/ ember.run prior to this issue :) thanks for the hard work/debugging effort!!! Hoping to land a fix for this tomorrow
