### ISSUE TITLE
Intention of "optional" reducer?

### ISSUE THREAD

**Issue by brettburley** [toranb/ember-redux#8]
I noticed that there's an optional reducer:
https://github.com/toranb/ember-redux/blob/master/app/reducers/optional.js

Your docs (http://www.ember-redux.com/configure/) mention:
> One reducer that is special to ember-redux is named optional.js and it allows you to audit any/all events that flow through dispatch. One example of this might be to write each event to a special audit list.

Is this any different than middleware? This seems to map to my understanding of middleware perfectly. So rather than the optional reducer, I think you could achieve the same adding a middleware like:
```
export default function auditMiddleware({ dispatch, getState }) {
  return (next) => (action) => {
    const entries = AuditLog.entries;
    entries.push({
      uuid: Ember.uuid(),
      action: action,
      state: getState()
    });
    return next(action);
  }
}
```

P.S. Not sure if there's a better place for more general discussions like these? I have a few other topics on best practices, etc. on using redux w/Ember, but not sure where best to discuss.

**Comment by toranb** [comment]
@brettburley excellent example! I think the "optional" reducer was truly an artifact of my early misunderstanding about how middleware/ and enhancers worked. My original "time travel" example was built using that optional function (it worked well enough but wasn't the correct approach).

I could remove the documentation on it if you think it's truly not adding anything valuable. After learning about enhancers I wanted to see if having a reducer that wrapped any dispatch was needed/useful. I assume you would agree it's not at this point?

If so I can remove the docs on this extension point for sure - to be semver friendly I'll most likely leave the function in place as-is until a v2.0 release some time later this year in which case we could deprecate it/etc

About discussion - this is a fine place at the moment. I'm thinking I should reach out to the slack group and see what it would take to get a channel for `ember-redux` so we could do dev discussions if nothing else

**Comment by toranb** [comment]
I reworded the description in the docs so people would better understand why this exists. I also plan to deprecate it in v2 if we don't find it's helpful
