### ISSUE TITLE
Make the store a Service

### ISSUE THREAD

**Issue by samselikoff** [toranb/ember-redux#9]
I enjoyed our conversations at EmberConf, and while I'm still not yet convinced of the merit of this integration (I think effort would be better spent on bringing Redux's ideas into Ember Data directly), I'm glad you're still pursuing it.

As long as you are, what do you think of making the Redux store an Ember Service? I'm all for bringing new ideas into Ember but I think it's good to leverage idiomatic Ember design where possible. Ember services are already global singletons and are a perfect fit for a global Redux store.

Reducers go in `/app/reducers`, and export either functions or arrays of functions. `ember-redux` would define a Redux store service (`/addon/services/store`), which reads in the reducers automatically and configures the store. Any component that needs state from the store, or needs to dispatch actions to it, can just use dependency injection:

```js
export default Ember.Component.extend({
    store: Ember.inject.service(),

    watchStore: Ember.on('init', function() {
        this.get('store').subscribe(() => {
            this.notifyPropertyChange('number');
        });
    },

    number: Ember.computed(function() {
        return this.get('store').getState();
    }),

    actions: {
        add() {
            this.get('store').dispatch({type: 'ADD'});
        }
    },

    layout: hbs`
      {{number}}
      <button onclick={{action "add"}}>add</button>
    `
});
```

Thoughts?

**Comment by samselikoff** [comment]
I see `connect` is intended to do some of this heavy lifting, but I still think it'd be nice to be able to inject the store (just like in Ember Data) if people want to use normal Ember actions & CPs to interact with the data.

**Comment by toranb** [comment]
@samselikoff I totally agree that the functional look of ember apps using `connect` won't be everyone's cup of tea ...so for everyone else the `core` is just an ember service as you suggested :)

https://github.com/toranb/ember-redux/blob/master/app/services/redux.js#L11

Here is your example from above (slightly) tweaked to use the correct service name. Let me know if this doesn't work / or you run into trouble using it like this.

```js
export default Ember.Component.extend({
    redux: Ember.inject.service('redux'),
    watchStore: Ember.on('init', function() {
        var redux = this.get('redux');
        redux.subscribe(() => {
            this.notifyPropertyChange('number');
        });
    },
    number: Ember.computed(function() {
        var redux = this.get('redux');
        return redux.getState();
    }),
    actions: {
        add: function() {
            var redux = this.get('redux');
            redux.dispatch({type: 'ADD'});
        }
    },
    layout: hbs`
      {{number}}
      <button onclick={{action "add"}}>add</button>
    `
});
```

**Comment by samselikoff** [comment]
Ah, I missed that. Thanks! I'm wondering if the docs on the homepage should show it being used like this, I know if I ever came into an app using this I'd prefer to see it done this way. It also saves users the boilerplate of setting up the store.
